import math
from typing import Literal

import torch
from isaaclab.utils.math import quat_from_euler_xyz

from DoorOpening.constants.robot_constants import FRANKA_DEFAULT_JOINT_POS, FRANKA_JOINT_NAMES, CAMERA_JOINT_DEFAULT_VALUES, CAMERA_JOINT_VALUES_WHEN_SEARCHING_HINGE, CAMERA_JOINT_VALUES_WHEN_OBSERVING_LEFT
from DoorOpening.utils.state_machine.api import compute_base_joint, get_board_edge, get_hinge_pos, open_hand, solve_ik

HandleSide = Literal["right", "left"]


def get_rotation_quat(roll, pitch, yaw, device):
    return quat_from_euler_xyz(
        roll=torch.tensor([[roll]], device=device),
        pitch=torch.tensor([[pitch]], device=device),
        yaw=torch.tensor([[yaw]], device=device),
    ).squeeze(0)


def _make_pose(position: torch.Tensor, quat: torch.Tensor) -> torch.Tensor:
    return torch.cat([position, quat], dim=-1)


def _append_state(
    robot_traj: list[torch.Tensor],
    door_traj: list[torch.Tensor],
    key_indices: list[int],
    q_robot: torch.Tensor,
    q_door: torch.Tensor,
    *,
    mark_keyframe: bool,
) -> None:
    robot_traj.append(q_robot.clone())
    door_traj.append(q_door.clone())
    if mark_keyframe:
        key_indices.append(len(robot_traj) - 1)


def _rotate_xy_clockwise(x_offset: float, y_offset: float, theta: torch.Tensor) -> tuple[torch.Tensor, torch.Tensor]:
    c = torch.cos(theta)
    s = torch.sin(theta)
    return x_offset * c + y_offset * s, -x_offset * s + y_offset * c


def _rotate_xy_counterclockwise(x_offset: float, y_offset: float, theta: torch.Tensor) -> tuple[torch.Tensor, torch.Tensor]:
    c = torch.cos(theta)
    s = torch.sin(theta)
    return x_offset * c - y_offset * s, x_offset * s + y_offset * c


def _init_planner_state(robot_initial_q, door_initial_q):
    robot_traj: list[torch.Tensor] = []
    door_traj: list[torch.Tensor] = []
    key_idx_in_key_indices: list[int] = []

    q_robot = robot_initial_q.clone()
    q_door = door_initial_q.clone()

    _append_state(
        robot_traj,
        door_traj,
        key_idx_in_key_indices,
        q_robot,
        q_door,
        mark_keyframe=False,
    )

    return q_robot, q_door, robot_traj, door_traj, key_idx_in_key_indices


def state_machine_offline_push_door(
    robot_urdf_path,
    door_urdf_path,
    robot_initial_pose,   # (1, 7) world
    door_initial_pose,    # (1, 7) world
    robot_initial_q,      # (ndof,)
    door_initial_q,       # (2,) [board, hinge]
    *,
    handle_side: HandleSide = "right",
    device="cpu",
):
    """
    Offline planner for push-type doors generated by generate_randomized_doors.py.

    The door joint convention matches the pull planner: q_door is [board, hinge].
    Generated push doors flip the board joint axis in the URDF, so positive board
    angle still means "open" from the planner's point of view.
    """

    if handle_side == "right":
        return state_machine_offline_push_right_door(
            robot_urdf_path,
            door_urdf_path,
            robot_initial_pose,   # (1, 7) world
            door_initial_pose,    # (1, 7) world
            robot_initial_q,      # (ndof,)
            door_initial_q,       # (2,) [board, hinge]
        )
    else:
        return state_machine_offline_push_left_door(
            robot_urdf_path,
            door_urdf_path,
            robot_initial_pose,   # (1, 7) world
            door_initial_pose,    # (1, 7) world
            robot_initial_q,      # (ndof,)
            door_initial_q,       # (2,) [board, hinge]
        )


def state_machine_offline_push_right_door(
    robot_urdf_path,
    door_urdf_path,
    robot_initial_pose,   # (1, 7) world
    door_initial_pose,    # (1, 7) world
    robot_initial_q,      # (ndof,)
    door_initial_q,       # (2,) [board, hinge]
    *,
    device="cpu",
):
    """
    Offline planner for push-type doors generated by generate_randomized_doors.py.

    The door joint convention matches the pull planner: q_door is [board, hinge].
    Generated push doors flip the board joint axis in the URDF, so positive board
    angle still means "open" from the planner's point of view.
    """

    q_robot, q_door, robot_traj, door_traj, key_idx_in_key_indices = _init_planner_state(
        robot_initial_q, door_initial_q
    )

    base_target_rot = robot_initial_pose[:, 3:].to(device).clone()
    default_palm_rot = get_rotation_quat(math.pi, math.pi, math.pi, device)
    push_palm_rot = get_rotation_quat(0.0, 0.0, -math.pi / 2, device)
    safe_open_hand_q = open_hand(1.0).to(q_robot.device)
    franka_default_q = torch.tensor(
        [FRANKA_DEFAULT_JOINT_POS[name] for name in FRANKA_JOINT_NAMES],
        device=device,
        dtype=q_robot.dtype,
    )

    _append_state(
        robot_traj,
        door_traj,
        key_idx_in_key_indices,
        q_robot,
        q_door,
        mark_keyframe=True,
    )

    # -------------------------
    # Step 0: Observe
    # -------------------------

    # q_robot[3: 10] = franka_default_q
    # q_robot[:3] = torch.tensor([0.15, 0.2, 0])

    # q_robot[-6:] = torch.tensor(list(CAMERA_JOINT_VALUES_WHEN_SEARCHING_HINGE.values()))

    # _append_state(
    #     robot_traj,
    #     door_traj,
    #     key_idx_in_key_indices,
    #     q_robot,
    #     q_door,
    #     mark_keyframe=True,
    # )

    # -------------------------
    # Step 1: Pregrasp
    # -------------------------
    handle_pos = get_hinge_pos(
        door_urdf_path,
        door_initial_pose,
        q_door.unsqueeze(0),
    ).to(device)

    base_target_pos = handle_pos.clone()
    base_target_pos[:, 0] += 0.6
    # Base moved a little inward (toward door center, -y; was -0.3) so it doesn't sit out by the wall.
    base_target_pos[:, 1] += -0.35
    base_target_pose = _make_pose(base_target_pos, base_target_rot)

    palm_target_pos = handle_pos.clone()
    palm_target_pos[:, 0] += 0.40
    # Slightly inward (-y; was -0.20).
    palm_target_pos[:, 1] += -0.23
    palm_target_pos[:, 2] += 0.2
    palm_target_pose = _make_pose(palm_target_pos, default_palm_rot)

    q_robot[:10] = solve_ik(
        robot_urdf_path,
        q_robot[:10],
        palm_pose=palm_target_pose,
        base_pose=base_target_pose,
        robot_initial_pose=robot_initial_pose,
    )[0]

    q_robot[-6:] = torch.tensor(list(CAMERA_JOINT_DEFAULT_VALUES.values()))

    _append_state(
        robot_traj,
        door_traj,
        key_idx_in_key_indices,
        q_robot,
        q_door,
        mark_keyframe=True,
    )

    # -------------------------
    # Step 2: Move to grasp
    # -------------------------
    palm_target_pos = handle_pos.clone()
    # Grasp EE ~1.5 cm FORWARD (-x). Left/right nudge intentionally NOT applied on the push door
    # (only forward helps here); y stays at the prior -0.10.
    palm_target_pos[:, 0] += 0.035
    palm_target_pos[:, 1] += -0.10
    palm_target_pos[:, 2] += 0.08
    palm_target_pose = _make_pose(palm_target_pos, default_palm_rot)

    q_robot[:10] = solve_ik(
        robot_urdf_path,
        q_robot[:10],
        palm_pose=palm_target_pose,
        base_pose=base_target_pose,
        robot_initial_pose=robot_initial_pose,
    )[0]
    q_robot[10:26] = open_hand(0.7).to(q_robot.device)

    _append_state(
        robot_traj,
        door_traj,
        key_idx_in_key_indices,
        q_robot,
        q_door,
        mark_keyframe=True,
    )

    # -------------------------
    # Step 3: Rotate hinge (unlatch)
    # -------------------------
    q_door = torch.tensor([0.0, 1.0], device=device)

    palm_target_pose = palm_target_pose.clone()
    palm_target_pose[:, 1] += 0
    palm_target_pose[:, 2] -= 0.08
    palm_target_pose[:, 3:] = get_rotation_quat(
        math.pi,
        math.pi,
        math.pi + 0.20,
        device,
    )

    q_robot[:10] = solve_ik(
        robot_urdf_path,
        q_robot[:10],
        palm_pose=palm_target_pose,
        base_pose=base_target_pose,
        robot_initial_pose=robot_initial_pose,
    )[0]

    _append_state(
        robot_traj,
        door_traj,
        key_idx_in_key_indices,
        q_robot,
        q_door,
        mark_keyframe=True,
    )

    # -------------------------
    # Step 4: Open the door farther while holding the handle and keeping base clearance
    # -------------------------
    push_theta_start = 0.20
    push_theta_stop = 1.50
    push_theta_step = 0.10
    hold_palm_rot_roll_base = math.pi

    for theta in torch.arange(
        push_theta_start,
        push_theta_stop + 1e-6,
        push_theta_step,
        device=device,
    ):
        q_door = torch.tensor([theta.item(), 0.0], device=device)

        handle_pos = get_hinge_pos(
            door_urdf_path,
            door_initial_pose,
            q_door.unsqueeze(0),
        ).to(device)

        base_target_pos = handle_pos.clone()
        base_target_pos[:, 0] += 0.55
        base_target_pos[:, 1] = 0.05
        base_target_pose = _make_pose(base_target_pos, base_target_rot)

        # Offset palm outward from panel surface — get_hinge_pos returns centroid at the panel
        push_palm_x_offset = 0.08
        push_palm_y_offset = 0.0
        palm_dx, palm_dy = _rotate_xy_counterclockwise(
            push_palm_x_offset,
            push_palm_y_offset,
            theta,
        )

        palm_target_pos = handle_pos.clone()
        palm_target_pos[:, 0] += palm_dx
        palm_target_pos[:, 1] += palm_dy
        palm_target_pos[:, 2] += 0.08
        hold_palm_rot = get_rotation_quat(
            hold_palm_rot_roll_base + 0.9 * theta.item(),
            math.pi * 4 / 5,
            math.pi + 0.10,
            device,
        )
        palm_target_pose = _make_pose(palm_target_pos, hold_palm_rot)

        q_robot[:10] = solve_ik(
            robot_urdf_path,
            q_robot[:10],
            palm_pose=palm_target_pose,
            base_pose=base_target_pose,
            robot_initial_pose=robot_initial_pose,
            num_attempts=1,  # loop body: single seed for continuity (no random-restart branch jumps)
        )[0]
        # Grasp the handle until the door is cracked open (~0.4 rad), then relax to a PARTLY
        # open hand (not fully open) and push the rest of the way with it.
        if theta.item() < 0.4:
            q_robot[10:26] = open_hand(0.7).to(q_robot.device)
        else:
            q_robot[10:26] = open_hand(0.85).to(q_robot.device)

        _append_state(
            robot_traj,
            door_traj,
            key_idx_in_key_indices,
            q_robot,
            q_door,
            mark_keyframe=False,
        )

    key_idx_in_key_indices.append(len(robot_traj) - 1)

    # -------------------------
    # Step 4.5: Base moves forward; arm IK keeps EE at handle world position.
    # We pin the base joints directly THEN solve IK with base_pose=None so the
    # IK cannot pull the base back while trying to reach the handle.
    # -------------------------
    door_center_pos = door_initial_pose[:, :3].to(device).clone()
    release_fwd_base_pos = door_center_pos.clone()
    release_fwd_base_pos[:, 0] += -0.8
    release_fwd_base_pos[:, 1] += 0.05
    release_fwd_base_pose = _make_pose(release_fwd_base_pos, base_target_rot)

    new_base_joints = compute_base_joint(
        robot_initial_pose[..., :3], robot_initial_pose[..., 3:], release_fwd_base_pose
    ).squeeze()
    q_robot[:3] = new_base_joints

    q_robot[:10] = solve_ik(
        robot_urdf_path,
        q_robot[:10],
        palm_pose=palm_target_pose,
        base_pose=None,
        robot_initial_pose=robot_initial_pose,
    )[0]
    q_robot[:3] = new_base_joints  # re-pin base in case IK drifted it
    q_robot[10:26] = safe_open_hand_q

    _append_state(
        robot_traj,
        door_traj,
        key_idx_in_key_indices,
        q_robot,
        q_door,
        mark_keyframe=True,
    )

    # -------------------------
    # Step 5: Traverse through the doorway with arm still extended
    # -------------------------
    # traverse_mid_base_pos = door_center_pos.clone()
    # traverse_mid_base_pos[:, 0] += -0.8
    # traverse_mid_base_pos[:, 1] += 0.15
    # traverse_mid_base_pose = _make_pose(traverse_mid_base_pos, base_target_rot)

    # q_door = torch.tensor([push_theta_stop, 0.0], device=device)
    # q_robot[:10] = solve_ik(
    #     robot_urdf_path,
    #     q_robot[:10],
    #     palm_pose=None,
    #     base_pose=traverse_mid_base_pose,
    #     robot_initial_pose=robot_initial_pose,
    # )[0]
    # q_robot[10:26] = safe_open_hand_q

    # _append_state(
    #     robot_traj,
    #     door_traj,
    #     key_idx_in_key_indices,
    #     q_robot,
    #     q_door,
    #     mark_keyframe=True,
    # )

    # -------------------------
    # Step 6: Finish traversing past the doorway with a smooth interpolated base sweep (like the
    # pull planner), then tuck the arm. palm_pose=None -> only the base moves each step; the arm
    # holds its config until the final step tucks it and closes the door.
    # -------------------------
    traverse_far_base_pos = door_center_pos.clone()
    traverse_far_base_pos[:, 0] += -1.5
    traverse_far_base_pos[:, 1] += 0.25

    traverse_steps = 8
    for traverse_step in range(1, traverse_steps + 1):
        frac = traverse_step / traverse_steps
        step_base_pos = release_fwd_base_pos + frac * (traverse_far_base_pos - release_fwd_base_pos)
        step_base_pose = _make_pose(step_base_pos, base_target_rot)
        q_robot[:10] = solve_ik(
            robot_urdf_path,
            q_robot[:10],
            palm_pose=None,
            base_pose=step_base_pose,
            robot_initial_pose=robot_initial_pose,
            num_attempts=1,  # loop body: single seed for continuity (no random-restart branch jumps)
        )[0]
        q_robot[10:26] = safe_open_hand_q
        if traverse_step == traverse_steps:
            q_robot[3:10] = franka_default_q
            q_door = torch.tensor([0.0, 0.0], device=device)
        _append_state(
            robot_traj,
            door_traj,
            key_idx_in_key_indices,
            q_robot,
            q_door,
            mark_keyframe=(traverse_step == traverse_steps),
        )

    return robot_traj, door_traj, key_idx_in_key_indices

def state_machine_offline_push_left_door(
    robot_urdf_path,
    door_urdf_path,
    robot_initial_pose,   # (1, 7) world
    door_initial_pose,    # (1, 7) world
    robot_initial_q,      # (ndof,)
    door_initial_q,       # (2,) [board, hinge]
    *,
    device="cpu",
):
    """
    Offline planner for push-type doors generated by generate_randomized_doors.py.

    The door joint convention matches the pull planner: q_door is [board, hinge].
    Generated push doors flip the board joint axis in the URDF, so positive board
    angle still means "open" from the planner's point of view.
    """

    q_robot, q_door, robot_traj, door_traj, key_idx_in_key_indices = _init_planner_state(
        robot_initial_q, door_initial_q
    )

    base_target_rot = robot_initial_pose[:, 3:].to(device).clone()
    default_palm_rot = get_rotation_quat(math.pi, math.pi, math.pi, device)
    push_palm_rot = get_rotation_quat(0.0, 0.0, -math.pi / 2, device)
    safe_open_hand_q = open_hand(1.0).to(q_robot.device)
    franka_default_q = torch.tensor(
        [FRANKA_DEFAULT_JOINT_POS[name] for name in FRANKA_JOINT_NAMES],
        device=device,
        dtype=q_robot.dtype,
    )

    _append_state(
        robot_traj,
        door_traj,
        key_idx_in_key_indices,
        q_robot,
        q_door,
        mark_keyframe=True,
    )

    # -------------------------
    # Step 0: Observe
    # -------------------------

    # q_robot[3: 10] = franka_default_q
    # q_robot[:3] = torch.tensor([0.15, 0.2, 0])

    # q_robot[-6:] = torch.tensor(list(CAMERA_JOINT_VALUES_WHEN_SEARCHING_HINGE.values()))

    # _append_state(
    #     robot_traj,
    #     door_traj,
    #     key_idx_in_key_indices,
    #     q_robot,
    #     q_door,
    #     mark_keyframe=True,
    # )

    # -------------------------
    # Step 1: Pregrasp
    # -------------------------
    handle_pos = get_hinge_pos(
        door_urdf_path,
        door_initial_pose,
        q_door.unsqueeze(0),
    ).to(device)

    base_target_pos = handle_pos.clone()
    base_target_pos[:, 0] += 0.55
    # Base moved a little inward toward the door center (+y; was 0.25) so it doesn't sit out by the wall.
    base_target_pos[:, 1] += 0.33
    base_target_pose = _make_pose(base_target_pos, base_target_rot)

    palm_target_pos = handle_pos.clone()
    palm_target_pos[:, 0] += 0.35
    # Slightly inward (+y; was 0.15).
    palm_target_pos[:, 1] += 0.18
    palm_target_pos[:, 2] += 0.25
    palm_target_pose = _make_pose(palm_target_pos, default_palm_rot)

    q_robot[:10] = solve_ik(
        robot_urdf_path,
        q_robot[:10],
        palm_pose=palm_target_pose,
        base_pose=base_target_pose,
        robot_initial_pose=robot_initial_pose,
    )[0]

    q_robot[-6:] = torch.tensor(list(CAMERA_JOINT_VALUES_WHEN_OBSERVING_LEFT.values()))

    _append_state(
        robot_traj,
        door_traj,
        key_idx_in_key_indices,
        q_robot,
        q_door,
        mark_keyframe=True,
    )

    # -------------------------
    # Step 2: Move to grasp
    # -------------------------
    palm_target_pos = handle_pos.clone()
    # Grasp EE ~1.5 cm FORWARD (-x). Left/right nudge intentionally NOT applied on the push door
    # (only forward helps here); y stays at the prior 0.03.
    palm_target_pos[:, 0] += 0.025
    palm_target_pos[:, 1] += 0.03
    palm_target_pos[:, 2] += 0.10
    palm_target_pose = _make_pose(palm_target_pos, default_palm_rot)

    q_robot[:10] = solve_ik(
        robot_urdf_path,
        q_robot[:10],
        palm_pose=palm_target_pose,
        base_pose=base_target_pose,
        robot_initial_pose=robot_initial_pose,
    )[0]
    q_robot[10:26] = open_hand(0.7).to(q_robot.device)

    _append_state(
        robot_traj,
        door_traj,
        key_idx_in_key_indices,
        q_robot,
        q_door,
        mark_keyframe=True,
    )

    # -------------------------
    # Step 3: Rotate hinge (unlatch)
    # -------------------------
    q_door = torch.tensor([0.0, 1.0], device=device)

    palm_target_pose = palm_target_pose.clone()
    palm_target_pose[:, 1] += 0.00
    palm_target_pose[:, 2] -= 0.08
    palm_target_pose[:, 3:] = get_rotation_quat(
        math.pi,
        math.pi,
        math.pi - 0.20,
        device,
    )

    q_robot[:10] = solve_ik(
        robot_urdf_path,
        q_robot[:10],
        palm_pose=palm_target_pose,
        base_pose=base_target_pose,
        robot_initial_pose=robot_initial_pose,
    )[0]

    _append_state(
        robot_traj,
        door_traj,
        key_idx_in_key_indices,
        q_robot,
        q_door,
        mark_keyframe=True,
    )

    # -------------------------
    # Step 4: Open the door farther while holding the handle and keeping base clearance
    # -------------------------
    push_theta_start = 0.20
    push_theta_stop = 1.50
    push_theta_step = 0.10
    hold_palm_rot_roll_base = math.pi

    # Retract active perception arms to safe range
    q_robot[-6:] = torch.tensor(list(CAMERA_JOINT_DEFAULT_VALUES.values()))

    for theta in torch.arange(
        push_theta_start,
        push_theta_stop + 1e-6,
        push_theta_step,
        device=device,
    ):
        q_door = torch.tensor([theta.item(), 0.0], device=device)

        handle_pos = get_hinge_pos(
            door_urdf_path,
            door_initial_pose,
            q_door.unsqueeze(0),
        ).to(device)

        base_target_pos = handle_pos.clone()
        base_target_pos[:, 0] += 0.55
        base_target_pos[:, 1] = -0.1
        base_target_pose = _make_pose(base_target_pos, base_target_rot)

        # Offset palm outward from panel surface — left door swings clockwise so rotate offset clockwise
        push_palm_x_offset = 0.08
        push_palm_y_offset = 0.0
        palm_dx, palm_dy = _rotate_xy_clockwise(
            push_palm_x_offset,
            push_palm_y_offset,
            theta,
        )

        palm_target_pos = handle_pos.clone()
        palm_target_pos[:, 0] += palm_dx
        palm_target_pos[:, 1] += palm_dy
        palm_target_pos[:, 2] += 0.08
        hold_palm_rot = get_rotation_quat(
            hold_palm_rot_roll_base - 0.9 * theta.item(),
            math.pi * 4 / 5,
            math.pi - 0.10,
            device,
        )
        palm_target_pose = _make_pose(palm_target_pos, hold_palm_rot)

        q_robot[:10] = solve_ik(
            robot_urdf_path,
            q_robot[:10],
            palm_pose=palm_target_pose,
            base_pose=base_target_pose,
            robot_initial_pose=robot_initial_pose,
            num_attempts=1,  # loop body: single seed for continuity (no random-restart branch jumps)
        )[0]
        # Grasp the handle until the door is cracked open (~0.4 rad), then relax to a PARTLY
        # open hand (not fully open) and push the rest of the way with it.
        if theta.item() < 0.4:
            q_robot[10:26] = open_hand(0.7).to(q_robot.device)
        else:
            q_robot[10:26] = open_hand(0.85).to(q_robot.device)

        _append_state(
            robot_traj,
            door_traj,
            key_idx_in_key_indices,
            q_robot,
            q_door,
            mark_keyframe=False,
        )

    key_idx_in_key_indices.append(len(robot_traj) - 1)

    # -------------------------
    # Step 4.5: Base moves forward while EE stays fixed at handle world position
    # -------------------------
    door_center_pos = door_initial_pose[:, :3].to(device).clone()
    release_fwd_base_pos = door_center_pos.clone()
    release_fwd_base_pos[:, 0] += -0.8
    release_fwd_base_pos[:, 1] += -0.05
    release_fwd_base_pose = _make_pose(release_fwd_base_pos, base_target_rot)

    new_base_joints = compute_base_joint(
        robot_initial_pose[..., :3], robot_initial_pose[..., 3:], release_fwd_base_pose
    ).squeeze()
    q_robot[:3] = new_base_joints

    q_robot[:10] = solve_ik(
        robot_urdf_path,
        q_robot[:10],
        palm_pose=palm_target_pose,
        base_pose=None,
        robot_initial_pose=robot_initial_pose,
    )[0]
    q_robot[:3] = new_base_joints  # re-pin base in case IK drifted it
    q_robot[10:26] = safe_open_hand_q

    _append_state(
        robot_traj,
        door_traj,
        key_idx_in_key_indices,
        q_robot,
        q_door,
        mark_keyframe=True,
    )

    # -------------------------
    # Step 6: Finish traversing past the doorway with a smooth interpolated base sweep (like the
    # pull planner), then tuck the arm. palm_pose=None -> only the base moves each step; the arm
    # holds its config until the final step tucks it and closes the door.
    # -------------------------
    traverse_far_base_pos = door_center_pos.clone()
    traverse_far_base_pos[:, 0] += -1.5
    traverse_far_base_pos[:, 1] += -0.25

    traverse_steps = 8
    for traverse_step in range(1, traverse_steps + 1):
        frac = traverse_step / traverse_steps
        step_base_pos = release_fwd_base_pos + frac * (traverse_far_base_pos - release_fwd_base_pos)
        step_base_pose = _make_pose(step_base_pos, base_target_rot)
        q_robot[:10] = solve_ik(
            robot_urdf_path,
            q_robot[:10],
            palm_pose=None,
            base_pose=step_base_pose,
            robot_initial_pose=robot_initial_pose,
            num_attempts=1,  # loop body: single seed for continuity (no random-restart branch jumps)
        )[0]
        q_robot[10:26] = safe_open_hand_q
        if traverse_step == traverse_steps:
            q_robot[3:10] = franka_default_q
            q_door = torch.tensor([0.0, 0.0], device=device)
        _append_state(
            robot_traj,
            door_traj,
            key_idx_in_key_indices,
            q_robot,
            q_door,
            mark_keyframe=(traverse_step == traverse_steps),
        )

    return robot_traj, door_traj, key_idx_in_key_indices
